### ISSUE TITLE
update user profile

### ISSUE THREAD

**Issue by lianaa98** [lianaa98/smart-todo-list#40]

**Comment by abeljlim** [comment]
working on /users/profile POST and /users/profile GET routes, and corresponding db functions

**Comment by lianaa98** [comment]
- [ ] Completed hard-code prototype page.

Plan: 

- [ ] pass in obj to GET user_profile page
- [ ] Edit POST profile
- [ ] render user name, pfp and daily reminder on user_index page

**Comment by lianaa98** [comment]
- [x] GET /users/me -> GET /users/profile -> GET /users/profile/edit 
- [ ] After POST /users/profile, redirect back to /users/me
- [ ] Style GET /users/profile
- [ ] Style GET /users/profile/edit
