### ISSUE TITLE
Rewrite bee button for category lists

### ISSUE THREAD

**Issue by lianaa98** [lianaa98/smart-todo-list#44]
Main todo list is working fine.
JQuery listener is skipping over 1 category list when the category lists are rendered.
Fix if have time.

**Comment by lianaa98** [comment]
Try refreshing the page and see if it fixes the problem

**Comment by abeljlim** [comment]
the bees in the category lists got toggled twice, or multiple times I think. I used tryLoadEventHandlers to make just one event handler to load per bee.
